import { useState } from 'react'
import { CATEGORIES } from './Trivia'
import './ConfigView.css'



// import { CATEGORIES } from './components/Trivia'

function DiffBtn({ label, variant, active, onClick }) {
  return (
    <button onClick={onClick}
      className={`diff-btn diff-btn--${variant} ${active ? 'diff-btn--active' : ''}`}>
      {label}
    </button>
  )
}

const SOURCES = [
  { id: 'trivia', label: '🌐 Live Trivia API', desc: 'Fresh questions from Open Trivia DB — free, no key needed.' },
  { id: 'upload', label: '📄 My Content',      desc: 'Questions generated by Claude AI from your uploaded notes.' },
]

export default function ConfigView({ config, setConfig, onStart, isGenerating, hasContent, detectedTopics }) {
  return (
    <div className="config-page">

      <div className="config-header">
        <h2>Configure Your Quiz</h2>
        <p>Choose your question source, difficulty, and number of questions.</p>
      </div>

      {/* Detected topics badge */}
      {detectedTopics && detectedTopics.length > 0 && (
        <div style={{ background: 'rgba(106,255,224,0.06)', border: '1px solid rgba(106,255,224,0.2)', borderRadius: 12, padding: '1rem 1.2rem', marginBottom: '1.4rem' }}>
          <div style={{ fontFamily: "'Syne',sans-serif", fontWeight: 600, fontSize: '0.82rem', color: 'var(--accent3)', marginBottom: '0.6rem', display: 'flex', alignItems: 'center', gap: 6 }}>
            🧠 Topics Detected from Your Content
          </div>
          <div style={{ display: 'flex', flexWrap: 'wrap', gap: 7 }}>
            {detectedTopics.map((t, i) => (
              <span key={i} style={{ padding: '4px 12px', borderRadius: 20, fontSize: '0.76rem', background: 'rgba(106,255,224,0.1)', border: '1px solid rgba(106,255,224,0.25)', color: 'var(--accent3)', fontWeight: 500 }}>
                {t}
              </span>
            ))}
          </div>
          <div style={{ fontSize: '0.75rem', color: 'var(--muted)', marginTop: '0.6rem' }}>
            Select <strong style={{ color: 'var(--text)' }}>📄 My Content</strong> below to generate questions on these topics.
          </div>
        </div>
      )}

      {/* Source selector */}
      <div>
        <span className="cfg-label">Question Source</span>
        <div className="source-grid">
          {SOURCES.map(src => {
            const active   = config.source === src.id
            const disabled = src.id === 'upload' && !hasContent
            return (
              <div key={src.id}
                onClick={() => !disabled && setConfig(c => ({ ...c, source: src.id }))}
                className={['source-card', active ? 'source-card--active' : '', disabled ? 'source-card--disabled' : ''].join(' ')}>
                <div className="source-card__title">{src.label}</div>
                <div className="source-card__desc">
                  {disabled ? '⚠️ Go to the Upload tab first to add your content.' : src.desc}
                </div>
              </div>
            )
          })}
        </div>
      </div>

      {/* Category — trivia only */}
      {config.source === 'trivia' && (
        <div className="cfg-select-wrap">
          <span className="cfg-label">Category</span>
          <select className="cfg-select" value={config.categoryId}
            onChange={e => setConfig(c => ({ ...c, categoryId: +e.target.value }))}>
            {CATEGORIES.map(cat => (
              <option key={cat.id} value={cat.id}>{cat.name}</option>
            ))}
          </select>
        </div>
      )}

      {/* Settings grid */}
      <div className="config-grid">

        <div className="cfg-card">
          <span className="cfg-label">Difficulty</span>
          <div className="diff-group">
            {[['easy','😊 Easy'],['medium','🎯 Medium'],['hard','🔥 Hard']].map(([k, l]) => (
              <DiffBtn key={k} label={l} variant={k} active={config.diff === k}
                onClick={() => setConfig(c => ({ ...c, diff: k }))} />
            ))}
          </div>
        </div>

        <div className="cfg-card">
          <span className="cfg-label">Number of Questions — {config.qCount}</span>
          <div className="range-row">
            <input type="range" min={3} max={20} step={1} value={config.qCount}
              onChange={e => setConfig(c => ({ ...c, qCount: +e.target.value }))} />
            <span className="range-val">{config.qCount}</span>
          </div>
        </div>

        <div className="cfg-card">
          <span className="cfg-label">Time per Question — {config.timeLimit}s</span>
          <div className="range-row">
            <input type="range" min={15} max={120} step={15} value={config.timeLimit}
              onChange={e => setConfig(c => ({ ...c, timeLimit: +e.target.value }))} />
            <span className="range-val">{config.timeLimit}s</span>
          </div>
        </div>

        <div className="cfg-card">
          <span className="cfg-label">Voice Narration</span>
          <div className="diff-group">
            <DiffBtn label="🔊 On"  variant="voice-on"  active={config.voiceOn}  onClick={() => setConfig(c => ({ ...c, voiceOn: true }))} />
            <DiffBtn label="🔇 Off" variant="voice-off" active={!config.voiceOn} onClick={() => setConfig(c => ({ ...c, voiceOn: false }))} />
          </div>
        </div>

      </div>

      {/* Source badge */}
      <div className="source-badge">
        {config.source === 'trivia' ? (
          <span className="source-badge__pill source-badge__pill--trivia">
            🌐 Questions fetched live from Open Trivia DB — free & always fresh
          </span>
        ) : (
          <span className="source-badge__pill source-badge__pill--ai">
            ✦ Claude AI will generate questions directly from your uploaded content
          </span>
        )}
      </div>

      <div className="start-wrap">
        <button className="btn-start" onClick={onStart} disabled={isGenerating}>
          {isGenerating ? '⏳ Generating Questions…' : 'Start Quiz ✦'}
        </button>
      </div>

    </div>
  )
}